name: "Deployment Action"
description: "Creates a GitHub Deployment"
author: "chrnorm"
branding:
  icon: arrow-up
  color: black
inputs:
  initial_status:
    description: "Initial status for the deployment"
    default: "pending"
    required: false
  ref:
    description: "The reference for the deployment"
    required: false
  token:
    description: "Github repository token"
    required: true
  target_url:
    description: "Target url location"
    required: false
  owner:
    description: "Owner of repo for deployment"
    required: false
  repo:
    description: "Repo for deployment"
    required: false
  payload:
    description: "Payload of deployment (JSON as string)"
    required: false
  description:
    description: "Descriptive message about the deployment"
    required: false
  environment:
    description: "The name of the environment for the deployment"
    default: "production"
    required: false
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "dist/index.js"
